FROM jazzdd/alpine-flask

RUN "mkdir -p /root/.pip/"
COPY pip.conf /root/.pip/
RUN "pip install tensorflow"


WORKDIR "/data"
COPY get_progress.py /
RUN chmod +x /get_progress.py
ENTRYPOINT ["/get_progress.py"]
