FROM tensorflow/tensorflow:latest

RUN mkdir -p ~/.pip/
COPY pip.conf ~/.pip/
RUN pip install --upgrade pip
RUN pip install flask


WORKDIR "/data"
COPY get_progress.py /
RUN chmod +x /get_progress.py
ENTRYPOINT ["/get_progress.py"]
