FROM tensorflow/tensorflow:latest

COPY gotty /usr/bin
RUN chmod +x /usr/bin/gotty


WORKDIR "/data"
COPY entrypoint_gotty.sh /usr/bin
RUN chmod +x /usr/bin/entrypoint_gotty.sh
ENTRYPOINT ["/usr/bin/entrypoint_gotty.sh"]
