FROM jazzdd/alpine-flask

RUN "mkdir -p ~/.pip/"
COPY pip.conf ~/.pip/
RUN "pip install tensorflow"


WORKDIR "/data"
COPY get_progress.py /
RUN chmod +x /get_progress.py
ENTRYPOINT ["/get_progress.py"]
