FROM tensorflow/tensorflow:latest

COPY gotty /usr/bin
RUN chmod +x /usr/bin/gotty


WORKDIR "/data"
ENTRYPOINT ["/usr/bin/gotty"]
CMD ["--permit-write","--credential", "$GOTTY_USER:$GOTTY_PASS", "--reconnect","/bin/bash"]
